[project]
name = "cartoon-sun-position"
version = "0.1.0"
description = "Generate a cartoonish sun position image for current time"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=12.1.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
